---
author: |
  | William Findlay
title: |
  | RELI2732 Notes Pre-Midterm
date: \today
bibliography: /home/housedhorse/.bibs/uni.bib
csl: /home/housedhorse/.bibs/ieee.csl
subparagraph: yes
header-includes: |
  ```{=latex}
  \usepackage{float}
  \usepackage{listings}
  \usepackage[hang,bf]{caption}
  \usepackage{framed}
  \usepackage[section]{placeins}
  \usepackage[dvipsnames,table]{xcolor}

  \usepackage{pifont}

  \allowdisplaybreaks

  % fancy headers/footers
  \makeatletter
  \usepackage{fancyhdr}
  \lhead{William Findlay et al.}
  \chead{}
  \rhead{\@title}
  \lfoot{}
  \cfoot{\thepage}
  \rfoot{}
  \renewcommand{\headrulewidth}{0.4pt}

  \usepackage{amsmath, amsfonts,amssymb, amsthm}
  \usepackage{siunitx}
  \usepackage[boxruled,lined,linesnumbered,titlenumbered]{algorithm2e}

  \usepackage{setspace}
  \usepackage{changepage}
  \usepackage[explicit]{titlesec}
  \usepackage{aliascnt}

  \floatplacement{figure}{!htbp}
  \floatplacement{table}{!htbp}
  \floatplacement{listing}{!htbp}
  \lstset{numbers=left,breaklines=true,frame=single,language=Python,captionpos=b,abovecaptionskip={\abovecaptionskip},
  belowcaptionskip={\belowcaptionskip},aboveskip=\intextsep,showstringspaces=false,identifierstyle=\color{Blue},
  commentstyle={\color{OliveGreen}},keywordstyle={\bfseries\color{Orange}}}
  \setlength{\captionmargin}{1in}

  \newgeometry{margin=1in}

  \newtheoremstyle{plain}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\itshape}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{definition}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{remark}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\itshape} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \theoremstyle{plain}

  % define theorem
  \newtheorem{theorem}{Theorem}[section]
  \providecommand*{\theoremautorefname}{Theorem}

  % define lemma
  \newtheorem{lemma}{Lemma}[section]
  \providecommand*{\lemmaautorefname}{Lemma}

  % define claim
  \newtheorem{claim}{Claim}[section]
  \providecommand*{\claimautorefname}{Claim}

  % define corollary
  \newtheorem{corollary}{Corollary}[section]
  \providecommand*{\corollaryautorefname}{Corollary}

  % define proposition
  \newtheorem{proposition}{Proposition}[section]
  \providecommand*{\propositionautorefname}{Proposition}

  % define conjecture
  \newtheorem{conjecture}{Conjecture}[section]
  \providecommand*{\conjectureautorefname}{Conjecture}

  \theoremstyle{remark}

  % define observation
  \newtheorem{observation}{Observation}[section]
  \providecommand*{\observationautorefname}{Observation}

  % define remark
  \newtheorem{remark}{Remark}[section]
  \providecommand*{\remarkautorefname}{Remark}

  \theoremstyle{definition}

  % define example
  \newtheorem{example}{Example}[section]
  \providecommand*{\exampleautorefname}{Example}

  % define definition
  \newtheorem{definition}{Definition}[section]
  \providecommand*{\definitionautorefname}{Definition}

  \newcommand{\blackbox}{\hfill$\blacksquare$}
  \usepackage{tikz}
  \newcommand*\circled[1]{\tikz[baseline=(char.base)]{
              \node[shape=circle,draw,inner sep=2pt] (char) {#1};}}

  \renewcommand{\labelitemi}{\large$\bullet$}
  \renewcommand{\labelitemii}{\ding{226}}
  \renewcommand{\labelitemiii}{\tiny$\blacksquare$}
  \renewcommand{\labelitemiv}{\small$\triangleright$}

  \titleformat{\paragraph} % command to change
  [runin]                  % shape  (runin, etc.)
  {\small\bfseries}              % format (bfseries, itshape, etc.)
  {}                       % label  (thesection, thesubsection, etc.)
  {0em}                    % separation between label and body
  {#1}        % before the body
  []                       % after the body

  \titleformat{\subparagraph} % command to change
  [runin]                  % shape  (runin, etc.)
  {\small\bfseries}              % format (bfseries, itshape, etc.)
  {}                       % label  (thesection, thesubsection, etc.)
  {0em}                    % separation between label and body
  {#1}        % before the body
  []                       % after the body

  \let\lil\lstinputlisting
  \usepackage{afterpage}
  \hypersetup{colorlinks, allcolors=., urlcolor=blue}

  \usepackage{etoolbox}% http://ctan.org/pkg/etoolbox
  \makeatletter
  \patchcmd{\lst@GLI@}% <command>
    {\def\lst@firstline{#1\relax}}% <search>
    {\def\lst@firstline{#1\relax}\def\lst@firstnumber{#1\relax}}% <replace>
    {\typeout{listings firstnumber=firstline}}% <success>
    {\typeout{listings firstnumber not set}}% <failure>
  \makeatother

  \usepackage{chngcntr}
  \counterwithin{figure}{section}
  \counterwithin{table}{section}

  \usepackage{booktabs}
  \usepackage{longtable}
  \usepackage{array}
  \usepackage{multirow}
  \usepackage{wrapfig}
  \usepackage{float}
  \usepackage{colortbl}
  \usepackage{pdflscape}
  \usepackage{tabu}
  \usepackage{threeparttable}
  \usepackage{threeparttablex}
  \usepackage[normalem]{ulem}
  \usepackage{makecell}
  \pagestyle{fancy}
  \usepackage{lipsum}
  ```
output:
  pdf_document:
    number_sections: true
    fig_crop: true
    fig_caption: true
    keep_tex: false
---
```{r,include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
```
\thispagestyle{empty}
\counterwithin{lstlisting}{section}
\newpage
\pagenumbering{roman}
\thispagestyle{plain}
\tableofcontents
\newpage
\thispagestyle{plain}
\listoffigures
\listoftables
\newpage
\pagenumbering{arabic}
\setcounter{page}{1}


# Introduction

## Definitions

### Brain Death
- **complete loss** of **all brain function**
  - both voluntary **AND**
  - involuntary
    - this is how it differs from a vegetative state
- used as a **legal indicator of death** in many jurisdictions

### Cosmology
- study of the **origins of life** and **the universe**
  - large scale properties of the universe as a whole
- what is the **religious culture's** view of the **universe**?

### Discourse Community
- group of people who **share** a common discourse (**common rhetorical goals**)
  - i.e., a **set of basic values and assumptions**
  - think Dungeons and Dragons players
- in the past discourse communities were a lot harder to form
  - limitations of media
  - if a story was **important enough** to share **it was a big deal**

### Epoch&eacute;
- suspension of judgement
- withholding of assent
- all **judgements** on **non-evident** matters are **suspended**
- role in **phenomenology**
  - block biases and assumptions
  - explain a phenomenon in terms of an inherent system of meaning
  - this predisposition **must be assumed** before phenomenological study
- don't worry about the **truth of stories**
  - worry about what they mean to people

### Iron Crutch Li
- **Li Tieguai**
- one of the **eight immortals** of **Taoist pantheon**
  - able to leave his body and commune with deities
  - while he was gone his body was **like a dead person**
  - always back within 7 days
- had an assistant
  - tasked with watching over his body
  - one day heard his mother was dying
  - decided to burn Li's body after 6 days instead of 7
    - but Li was not dead
    - when he came back he took the body of a beggar with an iron crutch

### Memento Mori
- "reminder of mortality"
- "remembrance of death"
- medieval Latin Christian
- **reflection on mortality**
  - consider **vanity of earthly life**
- the idea of being conscious of death
  - reflect on
    - lives
    - morality
    - place in the world

### Ontology
- study of **existence**
- what does it mean to exist?
  - **monistic**
    - one fundamental principle
    - e.g., scientism
  - **dualistic**
    - two fundamental principles
    - spirit and matter 

### Phenomenology
- consider **phenomena** as **distinct from being**
- focus on **consciousness** and **objects of direct experience**
- see definition of **Epoch&eacute;**
  - actively not deciding the truth of a claim
- in the context of religious studies
  - look at the **lived experience** of religious people
  - do not approach from an internal faith-based perspective

### Soteriology
- study of **religious doctrines** of **salvation**
- *soterios* = salvation in Latin
- Christianity
  - Christ is the savior
- some religions **don't have a soteriology**

### Taphophobia
- **fear** of being **buried alive**
- before medical advances, death was not always clear
  - safety coffins to address this
  - designs to allow the buried person to signal they are alive

### Thanatology
- **study** of **death**

### Theology
- how are gods understood?
- study of a **religion from within**

## Buddhist Parable of the Mustard Seed
- begins with a commentary on **reincarnation**
  - "flowing-on for a hundred thousand ages"
  - "evolved in this Buddha-era among gods and men"
  - **cosmological claim**
- Gotami-tissa
  - poor family
  - "skinny Gotami"
- Gotami has a son
  - people respect her now
  - **son dies**
    - this **drives her crazy**
    - "sorrow-to-the-point-of-madness"
    - she still feels attached to the body
- she desperately carries the body around
  - begs for medicine for her dead son
  - people revile her but she does not understand
- finally, a wise man tells her to **ask the Buddha for "medicine"**
 
### What Sort of Medicine is the Man Talking About?
- **advice/teaching** rather than physical medicine
- in fact, the Buddha tells her:
  - go to a house where they have not experienced death
  - ask them for a mustard seed
- Gotami searches for a family who has not experienced death
  - she cannot find one
  - so what use are their mustard seeds?
- finally she realizes the **futility of her madness**
  - death is a fact of life

## Religious Ritual (Characteristics)
- rituals
  - **invariant**
  - tied into **understanding** of an overall act
- religious rituals
  - **embedded in cultural systems**
  - performed
    - real audience
      - marriage
      - funeral
    - imagined audience
      - prayer
  - formalistic
    - **rules-governed**
  - traditionalistic
    - **invariant**
    - not that it **doesn't change**
    - rather that it **appears not to change**
- ritualization **posits the existence of** an **authoritative reality**
  - this reality **dictates the immediate situation**

### Effects of Ritual
- forms/**reinforces communities**
- connect actions with **authoritative reality**
- experiential and performative explanation of social realities
  - reverence of elders in Chinese religion
  - at a funeral, the youngest descendent acts as the deceased for a day
    - they get to experience reverence for the day

### Van Gennep's Rite of Passage
- involve a **change of social status**
  - e.g., Bar Mitzvah
- three stages
  1. **separation**
     - taken out of every day situation
     - separated from typical social circumstances
  1. **liminality**
     - between two different states
     - e.g., both boy and man at once
     - individuality is limited
  1. **reintegration**
     - often with special signs of having completed ritual
       - e.g., wedding rings


## Various Definitions of "Death"

### Traditional
- cessation of breath

### Chinese Culture
- Iron Crutch Li
- the dead were left out and venerated for a period of time
  - perhaps like Iron Crutch Li they were just visiting the gods

### Harvard
- a person can be declared dead IF
  - **brain function** is **irreversibly lost**
  - even though heart/lung activity is present due to **mechanical support**
- **brain death**

### Veatch's Four Possibilities
1. irreversible loss of the **flow of vital fluids**
1. irreversible **loss of soul**
1. irreversible **loss of brain function**
   - including self-regulation (involuntary function)
1. **loss of capacity for social function** due to **loss of higher brain function**

## Issues with Comparative Study of Religion
- there are *certain* cases for which this might be okay
  - keep it objective
  - focus on specific comparison/contrast
    - how does a given religion handle death?

### E.B. Tyler
- **primitive cultures**
  - somewhat pejorative
  - can one culture be more primitive than another?
  - inferior to another?

### Essentialism
- the assumption that there is **one original religion** from which **all others branch**
- **no evidence for this whatsoever**

# Indigenous Perspectives

## Definitions

### Animism
- elements of the natural world are
  - inhabited/animated by **spiritual beings**

### Psychic Unit of Humanity
- **all beings** across **all cultures** and **all time periods**
  - have the **same cognitive ability**
  - the **difference** is **culture**

### Numinous
- the **feeling** of **spiritual presence**
- defined by Rudolph Otto in *Idea of the Holy*
  - mysterium
    - mysterious
  - tremendum
    - scary
  - fascinans
    - fascinating
    - compelling
    - you *want* to engage

### Tupilaq
- totem thrown into sea by Inuit
  - sends a vengeful spirit to kill enemies

### Shaman
- **religious professional**
- **interacts** with the spiritual entities **directly**
- in many cultures
  - chosen by the spirits
  - mediate
    - healing
    - spiritual combat (dispel demons of disease)
  - non-ordinary states of consciousness
    - dreaming
    - ritual drumming
    - fasting
    - chanting
    - psychoactive substances

### Near-Death Experience
- often cited as evidence of cosmological claims
- Eben Alexander
  - had a near-death experience
  - wrote a book about it
    - "Proof of Heaven"
- causal explanations
  - emotional chock
- physical explanations
  - metabolic imbalance
  - drug overdose
  - lack of oxygen in brain

### Comensal Community
- **comensal**
  - sharing foood

## The Role of Affect in Religion
- **affect**
  - the way that humans **respond** to **phenomena**
- Rudolph Otto
  - the *Idea of the Holy* book
  - Otto **assumes** there is only **one** relationship between humans and spirit world
- early Japanese religion (Shinto)
  - *kami*
    - classification based on the **emotional impact** it has on people
  - it is through **stories** that the *kami* come into existence
    - what is worth telling a story about?
    - something that **impacts you**
- local cults develop
  - their **continued existence** is based on
    - **perceived efficacy** of the deity present
    - efficacy can be determined through **stories**

## Common Characteristics of Indigenous Religions (Basilov)

### Basilov Traits

1. **animism**
   - animation or spiritualization of the surrounding world
1. **connections** in nature
   - belief in all-embracing connections in nature
   - spirit-world is not discrete
1. **no separation** from surrounding world
   - depend on the surrounding world for survival
   - surrounding world **includes spirits**
1. the **cosmos** is **accessible**
   - spirit realms can be **accessed**
     - mostly **shamans**
     - possibly others
1. religion as **social consciousness**
   - creates **meaning** in the **bonds we have with each other**

### Cosmology
- **visible** world and **invisible** world
  - human beings possess **one or more souls**
  - diversity
    - is our world in **superposition** with the spirit world?
    - **or** do these spirits live **elsewhere**
- **animism**
  - some elements of the natural world are
    - inhabited by spiritual beings
    - or animated by spiritual beings
  - **what elements** of the world are interpreted this way?
    - Nayaka
      - object must be **tied to a human community**
    - early Japanese
      - *kami*: objects or elements of nature with **superior power**
      - awe-inspiring
      - humans can be *kami* (emperors)
      - Gods are also *kami*
- **religious practice** and **shamans**


## Souls in Indigenous Religions

### Multiplicity
- ancient China
  - **hun soul**
    - breath
    - animates the body
    - leaves on death
  - **po soul**
    - in the bones
    - remains in the body at burial
- Tibet
  - souls in **various parts** of the body
  - each soul is an **internal protective deity**
    - internal souls spread out
    - they *protect* you from illness
- Inuit
  - soul in the **larynx**
  - another soul on the **left side of the body**
  - also souls the size of **finger joints** that live in the **limbs**
  - about the size of a sparrow
  - help to animate the body
    - affective experience of **being alive** related to bodily **activities of these souls**
    - sore back could be because back soul exited body while sleeping

### Mobility
  - some souls can **leave the body**
  - not **always** the case that *every* soul can do this
    - ancient China
      - hun can leave
      - po stays
  - soul loss 
  - souls earned at specific points in life

### What Happens After Death to Souls
- **utopian vs locative**
  - utopian
    - you go to a **perfect place** discrete from the human world
    - heaven
  - locative
    - a real place
      - continued connection to this world
    - boundaries
    - Gurung people in Nepal
      - entry to land of ancestors on top of the Oble Dome

### Materiality
- specific **shapes**
  - Inuit
    - souls size of sparrow
    - shaped like little people
- susceptible to interventions
  - ancient China
    - dead honored at feast
    - dead eat and drink too
      - deceased can become drunk!
  - Inuit
    - souls can be **attacked** by magic
    - spirits can be used to attack people
      - attack their **souls** not their **bodies**
      - has an **effect** on the body
  - Soyot of Siberia
    - dip soul in hot water $\implies$ suffer fever
    - dip soul in cold water $\implies$ shivers
    - twist hands and legs of the soul $\implies$ pain in limbs
  - Hagen people of Papua New Guinea
    - sickness in the community
      - call upon the dead to help
      - say names of all the dead without leaving any out
    - if they forget a name, the spirit gets angry
      - send sickness in response
      - vindictive

## The Melpa Understanding of Souls

### Melpa Story
- eldest brother refuses to sacrifice sister's pig
- sister walks home and takes shelter in a sacrificial hut to sleep
  - dead mother's brother entered
  - hid her 
  - she saw spirits of the dead come for a meeting
    - locative
    - mobility
- spirits need to decide who to let die in a battle
  - nobody wants to give their men up
  - because their men need to give them sacrifice
- father decides to let the eldest brother die
  - because he refused to sacrifice his pig
- sister goes back to the brothers and warns them
  - shows them sacrificial meat as proof
- brothers ignored her advice
  - eldest brother dies in battle
- moral of the story:
  - dead are vengeful
  - dead hear, see, and know all
  - must honor them with sacrifices

## Wari Funeral Practice

### Mortuary Cosmology
- locative
  - ancestral realm at the bottom of deep water
  - no hunting
- ancestors emerge as boars and allow themselves to be hunted
  - support the living
  - the dead continue to **provide for the living**
- the dead are **responsible** for the **sustenance of the living**

### Death and Mourning
- from the moment of death until funeral's end
  - everyone screams
  - emotionally affective experience
- family
  - never allow the body to sit alone
- non-family
  - all other ritual obligations
  - prepare food
  - build pyre
- ritual piling
  - lay on the ground and pile on top of each other
  - until they pass out
- dismember body
  - place into cooking pots
  - inedible portions go to fire
  - non-family members eat the body

### Affect
- detachment from the dead
- the "negative experience of nostalgia"
- destroy all material evidence of the dead's existence
  - burn material possessions
  - name no longer used
  - mourners change aspects of their lives




# Death in the Ancient World

# Jewish Perspectives

# Christian Perspectives

# Muslim Perspectives
